---
id: debconf18
base_name: rethinking-of-debian-watch
tags:
- rabbit
- debconf18
- debian/watch
- uscan
presentation_date: 2018-08-03
version: 2018.08.03.1
licenses: 
- CC-BY-SA-4.0
slideshare_id:
speaker_deck_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kentaro Hayashi
  email: kenhys@gmail.com
  rubygems_user: kenhys
  slideshare_user: 
  speaker_deck_user: 
